# Generated by Django 3.0.6 on 2020-05-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20200520_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='document_text',
            field=models.TextField(default=''),
        ),
    ]
