# Generated by Django 3.0.6 on 2020-05-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_auto_20200520_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='patient_id',
            field=models.TextField(),
        ),
    ]
